### ISSUE TITLE
실행이 안됨

### ISSUE THREAD

**Issue by kwon-yw** [hoonkun/DungeonsEditor#3]
실행해도 0%에서 동작하질 않네요. 혹시 최신윈도우에서 안돌아가는 걸까요?
Windows 11, version 23H2

![image](https://github.com/hoonkun/DungeonsEditor/assets/102287172/eee01e66-d96d-498c-ab03-2b5ceb61f78e)

**Comment by hoonkun** [comment]
@kwon-yw 

안녕하세요, 확인이 늦어 죄송합니다.

해당 현상은 Minecraft Dungeons 가 시스템에 설치되어있지 않거나, 커스텀 경로(기본값인 C:\ 가 아닌 위치)에 설치되어있을 때 발생하는 것으로 확인됩니다. 유효한 범위 내에서 게임 설치파일을 찾지 못하면 커스텀 경로 입력 화면으로 이동해야하는데, Windows 환경에서 그러지 못하는 문제가 있어 수정해두려고 합니다. 

정확한 확인을 위해, Steam 또는 Minecraft Launcher 를 통해 마인크래프트 던전스를 설치하실 때 C 드라이브가 아닌 다른 경로에 설치하셨는지 여부를 회신해주실 수 있으실까요? 가능하시다면 게임의 설치 경로 전체를 회신해주시면 더 좋습니다.

**Comment by hoonkun** [comment]
우선 게임 파일을 찾을 수 없을 때 커스텀 경로 입력 화면으로 이동하지 않던 문제를 수정하고, 게임 파일을 더 많은 범위에서 찾도록 했습니다.

[이 릴리즈](https://github.com/hoonkun/DungeonsEditor/releases/tag/v1.0.3-EndRod)에서 계속 발생하는지 확인을 부탁드리고, 이 버전으로 실행했을 때는:
- 실행 시 커스텀 경로 입력 화면으로 넘어가거나
- 자동으로 게임 파일을 찾아 로드를 시작해야합니다.

만약 그렇지 않고 기존에 올려주신 이슈의 상황과 동일하다면 이슈를 reopen 해주세요.

**Comment by kwon-yw** [comment]
아이고 현생을 살다보니 저도 답변이 늦었네요. 네 기본경로가 아닌 제가 지정한 커스텀경로로 설치하고 있고, 오늘 다시한번 테스트 해보겠습니다.

**Comment by kwon-yw** [comment]
테스트를 해봤는데, 일단 경로입력은 잘되는걸 확인했습니다. 한글 지원되고, 인첸트를 넣을때 예외처리를 잘해놓으셔서 여러번 선택될수 없는 인첸트와 아이템 종류별 들어갈 수 없는 인첸트도 다 제외된건 정말 좋은데, 저장될때 충돌되서 강제 종료된 이후로 실행시 또 이전버전처럼 0%에서 움직이질 않네요 ㅠㅠ 경로관련 이슈는 아니라서 리오픈 하진 않았습니다.

**Comment by hoonkun** [comment]
앗 그렇군요... 적어주신 내용은 별도 이슈로 열어주시면 감사할 것 같습니다.
혹시 이슈 여실 때, 저장과 관련하여 조금 더 자세한 정보를 제시해주실 수 있으실까요? 혹은 다른 경로에 저장해보시고 관련 정보를 전달해주셔도 도움이 될 것 같습니다.

아마 툴을 완전히 제거하고 다시 설치하시면 0%에서 진행되지 않는 문제는 임시적으로 해소될 것이라고 생각하는데...
제 메인 개발 환경이 윈도우가 아니어서 증상 재현에 시간이 조금 걸릴 수도 있을 것 같습니다.

**Comment by hoonkun** [comment]
@kwon-yw 

윈도우 환경에서 확인했을 때 사용자 홈(/Users/사용자명/) 경로에 저장했을 때는 잘 저장되는 걸로 확인되었습니다.
설치 경로와 마찬가지로 별도 드라이브에 저장하셨는지 여부, 혹은 시스템 디렉터리와 같이 백신 및 운영체제 등에 의해 접근할 수 없는 디렉터리에 저장하셨는지 여부 등 저장 경로와 관련된 정보를 전달해주시면 도움이 될 것 같아요!
